### ISSUE TITLE
snapcraft error

### ISSUE THREAD

**Issue by zhex900** [ogra1/electron-kiosk-uc20#1]
Hi,

I get this error

```
+ npm install electron-packager
npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/5485/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> core-js@3.18.3 postinstall /root/parts/electron-helloworld/build/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> electron@15.3.0 postinstall /root/parts/electron-helloworld/build/node_modules/electron
> node install.js

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/var/lib/snapd/void/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@15.3.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@15.3.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

````

**Comment by zhex900** [comment]
A fresh build caused this error go away.
